@KafkaProducer_HostAddress = http://localhost:5008

GET {{KafkaProducer_HostAddress}}/weatherforecast/
Accept: application/json

###
POST {{{{KafkaProducer_HostAddress}}}}/publish
Content-Type: application/json

{
    "pensionerName": "Anders Hejlsberg",
    "age": 42,
    "email": "andershel@gmail.com",
    "phone": "+254709876566"
}