// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.3
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Avro
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.3")]
	public partial class PensionerDocs : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"PensionerDocs\",\"namespace\":\"Avro\",\"fields\":[{\"name\":\"doc" +
				"_name\",\"type\":\"string\"},{\"name\":\"doc_type\",\"type\":\"string\"}]}");
		private string _doc_name;
		private string _doc_type;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return PensionerDocs._SCHEMA;
			}
		}
		public string doc_name
		{
			get
			{
				return this._doc_name;
			}
			set
			{
				this._doc_name = value;
			}
		}
		public string doc_type
		{
			get
			{
				return this._doc_type;
			}
			set
			{
				this._doc_type = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.doc_name;
			case 1: return this.doc_type;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.doc_name = (System.String)fieldValue; break;
			case 1: this.doc_type = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
