// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.3
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Avro
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.3")]
	public partial class Pensioner : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""Pensioner"",""namespace"":""Avro"",""fields"":[{""name"":""name"",""type"":""string""},{""name"":""email"",""type"":""string""},{""name"":""phone"",""type"":""string""},{""name"":""award"",""type"":""string""},{""name"":""age"",""type"":""int""},{""name"":""attached_docs"",""default"":[],""type"":{""type"":""array"",""items"":{""type"":""record"",""name"":""PensionerDocs"",""namespace"":""Avro"",""fields"":[{""name"":""doc_name"",""type"":""string""},{""name"":""doc_type"",""type"":""string""}]}}}]}");
		private string _name;
		private string _email;
		private string _phone;
		private string _award;
		private int _age;
		private IList<Avro.PensionerDocs> _attached_docs;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return Pensioner._SCHEMA;
			}
		}
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				this._email = value;
			}
		}
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				this._phone = value;
			}
		}
		public string award
		{
			get
			{
				return this._award;
			}
			set
			{
				this._award = value;
			}
		}
		public int age
		{
			get
			{
				return this._age;
			}
			set
			{
				this._age = value;
			}
		}
		public IList<Avro.PensionerDocs> attached_docs
		{
			get
			{
				return this._attached_docs;
			}
			set
			{
				this._attached_docs = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.name;
			case 1: return this.email;
			case 2: return this.phone;
			case 3: return this.award;
			case 4: return this.age;
			case 5: return this.attached_docs;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.name = (System.String)fieldValue; break;
			case 1: this.email = (System.String)fieldValue; break;
			case 2: this.phone = (System.String)fieldValue; break;
			case 3: this.award = (System.String)fieldValue; break;
			case 4: this.age = (System.Int32)fieldValue; break;
			case 5: this.attached_docs = (IList<Avro.PensionerDocs>)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
